<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    '<small>Loading &hellip;</small>' => '<small>Chargement &hellip;</small>',
    'Actions' => 'Actions',
    'Active' => 'Actif',
    'Add Book' => 'Ajouter un livre',
    'All' => 'Tous',
    'Are you sure to delete this {item}?' => 'Voulez-vous vraiment supprimer ce {item}?',
    'Book Listing' => 'Liste des livres',
    'CSV' => 'CSV',
    'Clear selection' => 'Effacer la sélection',
    'Collapse' => 'Réduire',
    'Collapse All' => 'Réduire tout',
    'Comma Separated Values' => 'Valeurs séparées par des virgules',
    'Delete' => 'Supprimer',
    'Disable any popup blockers in your browser to ensure proper download.' => 'Désactivez tous les popup contextuelles dans votre navigateur pour garantir un téléchargement correct.',
    'Download Selected' => 'Télécharger la sélection',
    'Excel' => 'Excel',
    'Expand' => 'Etendre',
    'Expand All' => 'Etendre tout',
    'Export' => 'Exporter',
    'Export All Data' => 'Exporter toutes les données',
    'Export Page Data' => 'Exporter les données de page',
    'ExportWorksheet' => 'Exporter la feuille de travail',
    'Failed to update editable data due to an unknown server error' => 'Échec de la mise à jour des données modifiables en raison d\'une erreur de serveur inconnue',
    'Generated' => 'Généré',
    'Generating the export file. Please wait...' => 'Génération du fichier d\'exportation. S\'il vous plaît, attendez...',
    'Grid Export' => 'Exportation de grille',
    'HTML' => 'HTML',
    'Hyper Text Markup Language' => 'Hyper Text Markup Language',
    'Inactive' => 'Inactif',
    'Invalid editable index or model form name' => 'Nom de formulaire d\'index ou de modèle modifiable non valide',
    'Invalid or bad editable data' => 'Données modifiables invalides ou corrompues',
    'JSON' => 'JSON',
    'JavaScript Object Notation' => 'JavaScript Object Notation',
    'Krajee Solutions' => 'Krajee Solutions',
    'Krajee Yii2 Grid Export Extension' => 'Extension Krajee Yii2 Grid Export',
    'Library' => 'Librairie',
    'Microsoft Excel 95+' => 'Microsoft Excel 95+',
    'No data found' => 'Aucune donnée trouvée',
    'No valid editable model found' => 'Aucun modèle modifiable valide trouvé',
    'Ok to proceed?' => 'OK pour continuer?',
    'PDF' => 'PDF',
    'PDF export generated by kartik-v/yii2-grid extension' => 'Export PDF généré par l\'extension kartik-v / yii2-grid',
    'Page' => 'Page',
    'Portable Document Format' => 'Portable Document Format',
    'Request submitted! You may safely close this dialog after saving your downloaded file.' => 'Demande soumise! Vous pouvez fermer cette boîte de dialogue en toute sécurité après avoir enregistré votre fichier téléchargé.',
    'Reset Grid' => 'Réinitialiser la grille',
    'Resize table columns just like a spreadsheet by dragging the column edges.' => 'Redimensionnez les colonnes du tableau comme une feuille de calcul en faisant glisser les bords des colonnes.',
    'Show all data' => 'Afficher toutes les données',
    'Show first page data' => 'Afficher les données de la première page',
    'Showing <b>{begin, number}-{end, number}</b> of <b>{totalCount, number}</b> {totalCount, plural, one{{item}} other{{items}}}.' => 'Montrer  <b>{begin, number}-{end, number}</b> of <b>{totalCount, number}</b> {totalCount, plural, one{{item}} other{{items}}}.',
    'Tab Delimited Text' => 'Texte délimité par des tabulations',
    'Text' => 'Texte',
    'The CSV export file will be generated for download.' => 'Le fichier d\'exportation CSV sera généré pour téléchargement.',
    'The EXCEL export file will be generated for download.' => 'Le fichier d\'exportation EXCEL sera généré pour téléchargement.',
    'The HTML export file will be generated for download.' => 'Le fichier d\'exportation HTML sera généré pour téléchargement.',
    'The JSON export file will be generated for download.' => 'Le fichier d\'exportation JSON sera généré pour téléchargement.',
    'The PDF export file will be generated for download.' => 'Le fichier d\'exportation PDF sera généré pour téléchargement.',
    'The TEXT export file will be generated for download.' => 'Le fichier d\'exportation TEXT sera généré pour téléchargement.',
    'The page summary displays SUM for first 3 amount columns and AVG for the last.' => 'Le résumé de la page affiche SOMME pour les 3 premières colonnes de montant et MOYENNE pour la dernière.',
    'The table header sticks to the top in this demo as you scroll' => 'L\'en-tête du tableau reste en haut de cette démo lorsque vous faites défiler',
    'There are {totalCount} records. Are you sure you want to display them all?' => 'Il y a {totalCount} enregistrements. Voulez-vous vraiment les afficher tous?',
    'Total <b>{count, number}</b> {count, plural, one{{item}} other{{items}}}.' => 'Total <b>{count, number}</b> {count, plural, one{{item}} other{{items}}}.',
    'Update' => 'Mettre à jour',
    'View' => 'Voir',
    'Yii2 Grid Export (PDF)' => 'Exportation de grille Yii2 (PDF)',
    'export' => 'exportation',
    'grid-export' => 'exportation de grille',
    'item' => 'article',
    'items' => 'articles',
    'items-acc' => 'article-acc',
    'items-few' => 'article-few',
    'items-many' => 'article-many',
    'krajee, grid, export, yii2-grid, pdf' => 'krajee, grid, export, yii2-grid, pdf',
    '© Krajee Yii2 Extensions' => '© Krajee Yii2 Extensions',
];
